cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<order_item_id>[\w-]+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<order_item_id>[\w-]+)/$', views.cart_remove, name='cart_remove'),
]

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.contrib.auth import views
from . import views as index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^account/", include("allauth.urls")),
    url(r"^accounts/", include("allauth.urls")),
    url(r"^api/v1/", include("projeto_tg.api.urls")),
    url(r"^api/v1/auth/", include("djoser.urls.authtoken")),
    url(r'^social-auth/', include('social_django.urls', namespace="social")),
    # path('accounts/', include('django.contrib.auth.urls')),
    url(r'^$',index_view.index_view,name='home'),
    url(r'^cart/', include(('projeto_tg.cart.urls', 'cart'), namespace='cart')),
    url(r'event_carousel/',index_view.get_events),
    url(r'^event/', include('projeto_tg.evento.urls')),
    url(r'^profile/', include('projeto_tg.people.urls')),
    url(r'^order/', include('projeto_tg.order.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^search/autocomplete_city', index_view.autocomplete_city),
    url(r'^search/autocomplete', index_view.autocomplete)

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.LOCAL_MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from polymorphic.models import PolymorphicModel, PolymorphicManager
from taggit.models import TagBase, ItemBase
from django.utils.translation import ugettext_lazy as _
from django.db.models import Q, signals

# Create your models here.

class TopicCategory(models.Model):

  identifier = models.CharField(max_length=255, default="")
  slug = models.SlugField(max_length=50, unique=True, default="")
  description = models.TextField(default="")
  fa_class = models.CharField(max_length=64, default="fa-times")
  is_active = models.BooleanField(default=True)
  created_at = models.DateTimeField(auto_now_add=True)
  update_at = models.DateTimeField(auto_now=True)
  
  class Meta:
        ordering = ['-created_at']
        verbose_name_plural = "Categories"

  

class TopicType(models.Model):

  identifier = models.CharField(max_length=255, default="Público")
  description = models.TextField(default="")
  fa_class = models.CharField(max_length=64, default="fa-times")
  is_active = models.BooleanField(default=True) 
  created_at = models.DateTimeField(auto_now_add=True)
  update_at = models.DateTimeField(auto_now=True)
  
  class Meta:
        ordering = ['-created_at']
        verbose_name_plural = "Types"

class ResourceBase(PolymorphicModel, ItemBase):
  
  category_help_text = _("Categoria a qual o evento se encaixa")
  type_help_text = _("Tipo do evento")
  
  category = models.ForeignKey(
    TopicCategory,
    null=True,
    blank=True,
    help_text=category_help_text,
    on_delete=models.SET_NULL)
    
  type_event = models.ForeignKey(
    TopicType,
    null=True,
    blank=True,
    help_text=type_help_text,
    on_delete=models.SET_NULL)

class ResourceBaseManager(PolymorphicManager):
    def admin_contact(self):
        # this assumes there is at least one superuser
        superusers = get_user_model().objects.filter(is_superuser=True).order_by('id')
        if superusers.count() == 0:
            raise RuntimeError(
                'GeoNode needs at least one admin/superuser set')

        return superusers[0]

    def get_queryset(self):
        return super(
            ResourceBaseManager,
            self).get_queryset().non_polymorphic()

base/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load i18n avatar_tags %}
{% load bootstrap_tags %}

<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'projeto_tg/images/favicon.png' %}">
		<link href="{% static 'projeto_tg/css/bootstrap.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/bootstrap.min.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/bootstrap-grid.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/bootstrap-grid.min.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/bootstrap-reboot.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/bootstrap-reboot.min.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/css_slider.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/font-awesome.min.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/single.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/style.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/site.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/quill.snow.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/semantic.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/material.indigo-pink.min.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/getmdl-select.min.css' %}" rel="stylesheet" />
		<link href="{% static 'projeto_tg/css/material-components-web.min.css' %}" rel="stylesheet" />
	

		<script src="{% static 'projeto_tg/js/jquery-3.4.1.js' %}"></script>
		<script src="{% static 'projeto_tg/js/jquery.mask.js' %}"></script>
		<script src="{% static 'projeto_tg/js/jquery.mask.min.js' %}"></script>
		<script src="{% static 'projeto_tg/js/bootstrap.js' %}"></script>
		<script src="{% static 'projeto_tg/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'projeto_tg/js/bootstrap.bundle.js' %}"></script>
		<script src="{% static 'projeto_tg/js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'projeto_tg/js/angular.min.js' %}"></script>
		<script src="{% static 'projeto_tg/js/angular-sanitize.js' %}"></script>
		<script src="{% static 'projeto_tg/js/quill.js' %}"></script>
		<script src="{% static 'projeto_tg/js/material-components-web.min.js' %}"></script>
		<script src="{% static 'projeto_tg/js/material.min.js' %}"></script>
		<script src="{% static 'projeto_tg/js/getmdl-select.min.js' %}"></script>
		<script src="{% static 'projeto_tg/js/jquery.mask.js' %}"></script>
		<script src="{% static 'projeto_tg/js/ckeditor.js' %}"></script>

		<!-- Controllers -->
		<script src="{% static 'projeto_tg/js/angular-controllers/evento-controller.js' %}"></script>
		
		<title>{% block title %}Let's Party{% endblock %}</title>
	</head>
	<body ng-app="myApp">
			<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
					<a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'projeto_tg/images/logo.png' %}" width="80" /></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
						<span class="navbar-toggler-icon"></span>
					</button>
				
					<div class="row collapse navbar-collapse cold-md-12" id="conteudoNavbarSuportado">
							
						  <form class="form-inline col-md-8" action="{% url 'search_event' %}" method="GET">
								<input class="form-control col-md-5" autocomplete="off" type="text" id="id_q" name="q" placeholder="Pesquisar" onkeyup="autosearch(this)" url="autocomplete" aria-label="Pesquisar">
								<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" style="margin-left: 10px;" type="submit">Pesquisar</button>
							</form>

							{% with total_items=cart|length %}
								<a class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored " href="{% url 'cart:cart_detail' %}" role="button" style="margin-right:10px">
									<i class="fa fa-shopping-basket" aria-hidden="true"></i>
									<span class="badge badge-light">{{ total_items }}</span>
								</a>
							{% endwith %}
							{% if user.is_authenticated %}
								<div class="btn-group">
									<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									{% with full_name=user.first_name|add:' '|add:user.last_name %}
										{% if full_name.strip %}
											{{ full_name | truncatechars:20 }}
										{% else %}
											{{ user.username | truncatechars:20 }}
										{% endif %}
									{% endwith %}
									</button>
									<div class="dropdown-menu">
										<a class="dropdown-item" href="{% url 'profile_detail' username=user.username %}">Meu Perfil</a>
										<a class="dropdown-item" href="/order/">Minhas compras</a>
										<a class="dropdown-item" href="#"data-toggle="modal" role="button" data-target="#logout-modal">Sair</a>
									</div>
								</div>
								<a class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" href="{% url 'event_browse' %}" role="button" style="margin-left:10px"><i class="fa fa-plus fa-1x"></i>{% trans " Evento" %}</a>
							{% else %}
								<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" data-toggle="modal" role="button" data-target="#modal-options">{% trans "Login" %}</button>
								{% if not user.is_authenticated %}
									<a class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" href="#" data-toggle="modal" role="button" data-target="#modal-options" style="margin-left:10px"><i class="fa fa-plus fa-1x"></i>{% trans " Evento" %}</a>
								{% else %}
									<a class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" href="{% url 'event_browse' %}" role="button" style="margin-left:10px"><i class="fa fa-plus fa-1x"></i>{% trans " Evento" %}</a>
								{% endif %}
							{% endif %}

					</div>
			</nav>

			<div class="wrap">

				{% block middle %}
        {% endblock middle %}

			</div>

			{% block footer %}
				<section id="footer" style="margin-top:50px">

						<footer class="page-footer font-small blue">
								<div class="footer-copyright text-center py-3">© 2019 Copyright:
										<a href="https://mdbootstrap.com/education/bootstrap/"> Fatec</a>
								</div>
						</footer>

				</section>
			{% endblock footer %}

			<!--Modal Options -->
			{% if not user.is_authenticated %}
			<div class="modal fade " id="modal-options" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				{% include "account/modal_options.html" %}
			</div>
			{% endif %}
			<!-- Fim modal Options -->

      <!-- Modal Logout -->
			<div class="modal fade" id="logout-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				<div class="modal-dialog demo-card-wide mdl-card mdl-shadow--2dp" role="document">
					<div class="modal-content">
			
						<div class="mdl-card__title mdl-color--primary mdl-color-text--white">
							<h2 class="mdl-card__title-text">Sair</h2>
						</div>
			
						<form class="form-signin" role="form" action="{% url "account_logout" %}" method="post">
							<div class="modal-body">
									{% csrf_token %}
										<h2 class="page-title">{% trans "Log out" %}</h2>
										{% csrf_token %}
										<p>{% trans "Deseja realmente sair?" %}</p>
							</div>
							<div class="modal-footer">
								<div class="form-actions">
									<button type="submit" class="btn btn-primary">{% trans "Log out" %}</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
			<!-- Fim modal Logout -->

			{% block extra_script %}
				<script type="text/javascript">
					{% include 'autocomplete.js' %}
					window.flip = function(flip) {
						$('#cube').removeClass(); 
						$('#cube').addClass(flip);   
					}
					{% include 'login.js' %}
				</script>
			{% endblock extra_script %}
</body>
</html>

templates/carousel.html
{% load staticfiles %}

<div class="container" >
	<div class="row">
		<div class="MultiCarousel" data-items="1,3,5,6" data-slide="1" id="MultiCarousel"  data-interval="1000">
            <div class="MultiCarousel-inner">
                {% for evt in events_show %}
                <div class="item">
                    <div class="swiper-slide featured-event-box" style="margin: 20px;">
                        <a href="{% url 'event_detail' event=evt.id_hash %}" >
                            <div class="event-image-box" style="background-image: url('/uploaded/{{ evt.image_file }}');"></div>
                            <div class="event-name">
                                <p>{{ evt.title }}</p>
                            </div>
                            <div class="calendar-box">
                                <div class="calendar-month">{{ evt.month }}</div>
                                <div class="calendar-day">{{ evt.date.day }}</div>
                            </div>
                            <div class="event-local-box">
                                <div class="uppercase line">
                                    <p>{{ evt.address.city.name }} - {{ evt.address.city.sigla }}</p>
                                </div>
                                <div class="line"><i class="fa fa-clock-o color-grey" style="padding-right: 2px;"></i>13h <i class="fa fa-map-marker color-grey" style="padding: 10px;"></i>{{ evt.address.city.name }} , {{ evt.address.city.sigla }}</div>
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button class="btn btn-primary leftLst"><i class="fa fa-arrow-left"></i></button>
            <button class="btn btn-primary rightLst"><i class="fa fa-arrow-right"></i></button>
        </div>
	</div>
</div>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n avatar_tags %}

{% block middle %}
<div class="container">
	<section class="row panel panel-default col-md-12" style="margin-top: 100px;">
		<form class="form-inline col-md-4">
			<input class="form-control col-md-12" type="search" onkeyup="autosearch(this)" id="search_event" url="autocomplete" placeholder="Pesquisar por eventos" aria-label="Pesquisar por eventos">
		</form>
		<form class="form-inline col-md-4">
			<input name="search_city" class="form-control col-md-12" onkeyup="autosearch(this)" id="search_city" type="search" placeholder="Pesquisar por cidades" url="autocomplete_city" aria-label="Pesquisar por cidades">
		</form>
		<form class="form-inline col-md-4">
			<div class="btn-group">
				<select class="custom-select" id="inputGroupSelect01" style="min-width: 40px;">
					<option>Todas as datas</option>
					<option>Hoje</option>
					<option>Amanha</option>
					<option>Esta semana</option>
					<option>Este fim de semana</option>
					<option>Proxima semana</option>
					<option>Este mes</option>
				</select>
			</div>
			<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" style="margin-left: 10px;" type="submit">Pesquisar</button>
		</form>
		
	</section>
</div>
<div class="container">
	<section>
		<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="margin-top:50px">

			<ol class="carousel-indicators">
				<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
				<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
				<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
			</ol>

			<div class="carousel-inner">
				{% for event in events %}
				{% if event.id == 0 %}
				<div class="carousel-item active">
				{% else %}
				<div class="carousel-item">
				{% endif %}
					<div class="slide-thump owl-item row col-md-12">
						<img class="col-md-6" style="height:370px" src="uploaded/{{ event.image_file }}" alt="Primeiro Slide">

						<div class="col-xl-5 col-lg-6">
							<div class="banner-left-w3">
								<div class="container">

									<div class="banner-info_agile_w3ls">

										<h5>{{ event.title }}</h5>

										<h3 class="text-da mb-4">{{ event.short_description }}</h3>

										<div class="event-date pull-left">
												<span>{{ event.month }}</span>
												<div class="number">{{ event.date.day }}</div>
										</div>

										{% comment %} <p>{{ event.short_description }}</p> {% endcomment %}

										<a href="{% url 'event_detail' event=event.id_hash %}" class="button-w3ls active mt-5" style="margin-bottom:10px">Detalhes
											<span class="fa fa-caret-right ml-1" aria-hidden="true"></span>
										</a>

									</div>

								</div>
							</div>
						</div>
					</div>
					
				</div>
				{% endfor %}
			</div>

			<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Anterior</span>
			</a>

			<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="sr-only">Próximo</span>
			</a>

		</div>
	</section>
</div>

<div class="container">
	<section class="blog_w3ls py-5">
		<h5>Destaques</h5>
		<ul class="pagination form-inline" style="float:right;margin-top:-30px">
			{% if events.has_previous %}
				<li><a href="?page={{ events.previous_page_number }}"><i class="fa fa-arrow-left"></i></a></li>
			{% else %}
				<li class="disabled"><i class="fa fa-arrow-left"></i></li>
			{% endif %}
			{% for i in paginator.page_range %}
				{% if events.id == i %}
					<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
				{% else %}
					<li><a href="?page={{ i }}">{{ i }}</a></li>
				{% endif %}
			{% endfor %}
			{% if events.has_next %}
				<li><a href="?page={{ events.next_page_number }}"><i class="fa fa-arrow-right"></i></a></li>
			{% else %}
				<li class="disabled"><i class="fa fa-arrow-right"></i></li>
			{% endif %}
		</ul>
		<div class="row">
			{% for event in events %}
				<div class="col-lg-4 col-md-6">
					<div class="card border-0 med-blog owl-item">
						<div class="card-header p-0">
							<a href="{% url 'event_detail' event=event.id_hash %}">
								<img style="max-height:190px" class="card-img-bottom" src="uploaded/{{ event.image_file }}" alt="Card image cap">
							</a>
						</div>
						<div class="card-body border border-top-0">
							<h5 class="blog-title card-title m-0"><a href="{% url 'event_detail' event=event.id %}">{{ event.name }}</a></h5>
							<p class="mt-3">{{ event.short_description }}</p>
							{% comment %} <i class="fa {{ event.category.fa_class }}"></i>
							<i class="fa {{ event.type_event.fa_class }}"></i> {% endcomment %}
							<div class="event-date pull-left">
									<span>{{ event.month }}</span>
									<div class="number">{{ event.date.day }}</div>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</section>
</div>

<section>
	{% include 'carousel.html' %}
	<script>
		{% include 'carousel-script.js' %}
		{% include 'autocomplete.js' %}
		{% include "login.js" %}
	</script>
</section>

{% endblock middle %}