evento/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views



urlpatterns = [
    url(r'^$',
        views.index_view,
        name='event_browse'),
    url(r'^search/', views.search, name='search_event'),
    url(r'^search_for/city',views.get_cities, name="get_cities"),
    url(r'^(?P<event>[^/]*)$',views.event_detail, name="event_detail")
]

evento/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from projeto_tg.base.models import ResourceBase, ResourceBaseManager
from projeto_tg.endereco.models import Endereco
import uuid

class EventoManager(ResourceBaseManager):
  
    def __init__(self):
        models.Manager.__init__(self)

class Evento(ResourceBase):

  objects = EventoManager()
  name = models.CharField(
    help_text = "Nome pelo qual sera chamado o evento",
    null = False,
    unique = False,
    max_length=50)
  date = models.DateTimeField(
    help_text = "Data que foi criado o evento",
    null = True,
    unique = False
  )
  start_date = models.DateTimeField(
    help_text = "Data que começa o evento",
    null = True,
    unique = False
  )
  end_date = models.DateTimeField(
    help_text = "Data em que terminara o evento",
    null = True,
    unique = False
  )
  title = models.CharField(
    help_text="Titulo do evento",
    null=False,
    default="",
    max_length=40
  )
  short_description = models.CharField(
    help_text = "Pequeno resumo do evento",
    null = False,
    unique = False,
    max_length=500
  )
  description = models.TextField(
    help_text="Corpo do html com as informações do evento",
    null = False,
    default=""
  )
  image_file = models.FileField(
    help_text = "Imagem do evento",
    null = False,
    default="",
    upload_to = "events"
  )
  ticket_price = models.FloatField(
    help_text = "Preço de cada cupom",
    null = False,
    default = 0.0
  )
  price = models.DecimalField(max_digits=10, decimal_places=0, default=0.00)
  available = models.BooleanField(default=True)
  upload_session = models.ForeignKey('UploadSession', blank=True, null=True, on_delete=models.SET_NULL, default=None)
  address = models.ForeignKey(Endereco,null=True, blank=True,default=0, on_delete=models.SET_NULL)
  slug = models.SlugField(default='', blank=True)
  id_hash = models.TextField(default=str(uuid.uuid4()), unique=True)

  def save(self, *args, **kwargs):
    super().save(*args, **kwargs)

  class Meta:
    db_table = "eve_evento"
  
  def __str__(self):
      return self.title
    
  

class UploadSession(models.Model):

  
    date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    processed = models.BooleanField(default=False)
    error = models.TextField(blank=True, null=True)
    traceback = models.TextField(blank=True, null=True)
    context = models.TextField(blank=True, null=True)

evento/forms.py
from django import forms
from projeto_tg.evento.models import Evento


class DocumentForm(forms.ModelForm):
    
    class Meta:
        model = Evento
        fields = ('name',
                  'title',
                  'short_description',
                  'description',
                  'date', 
                  'image_file',
                  'start_date',
                  'end_date',
                  'price'
                  )

evento/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.db.models import Q
from .forms import DocumentForm
from .utils import event_upload

import json
from projeto_tg.evento.models import Evento
from projeto_tg.cidade.models import Cidade
from projeto_tg.cidade.models import Estado
from projeto_tg.cart.models import Cart
from projeto_tg.cart.forms import CartAddOrderItemForm

from projeto_tg.base.models import TopicCategory, TopicType
from .documents import EventDocument
from projeto_tg.endereco.forms import EnderecoForm
import datetime
import logging

logger = logging.getLogger(__name__)

@login_required
def index_view(request, template="evento_add.html"):
  cart = Cart(request)
  logger.error('Something went wrong!')
  if request.method == 'POST':
    form_address = EnderecoForm(request.POST)
    form = DocumentForm(request.POST, request.FILES)
    breakpoint()
    if form.is_valid():
      evento_saved, has_creat = event_upload(
          form.cleaned_data['image_file'],
          form.cleaned_data['name'],
          request.user,
          form.cleaned_data['date'],
          form.cleaned_data['title'],
          form.cleaned_data['short_description'],
          form.cleaned_data['description'],
          request.POST['category'],
          request.POST['type_event'],
          request.POST['price'],
          request.POST['street_name'],
          request.POST['number'],
          request.POST['cep'],
          form.cleaned_data['start_date'],
          form.cleaned_data['end_date'],
          request.POST['city']
      )
      return render(request, "evento_detail.html", {'event':evento_saved, 'cart': cart})
    return render(request, "evento_add.html")
  else:
    form = EnderecoForm()

    list_categories = TopicCategory.objects.all()
    list_types = TopicType.objects.all()
    list_state = Estado.objects.distinct('name','sigla')

    out = {
      'form': form,
      'categories': list_categories,
      'types': list_types,
      'list_state':list_state,
      'cart': cart
    }
    
    return render(request, template, out)


def get_events_carousel(request):
  event_list = Evento.objects.all()
  try:
    context = {
      'events' : event_list
    }
  except Exception as e:
    context = {
      'error': e
    }
  return HttpResponse(context, content_type='application/json')


def event_detail(request, event, template="evento_detail.html"):
  cart = Cart(request)
  event = Evento.objects.filter(id_hash__exact=event)
  out = {
    'event': event[0],
    'cart': cart
  }

  return render(request, template, out)

def search(request, template="evento_list.html"):
  cart = Cart(request)
  q = request.GET.get('q')
  event_search = Evento.objects.filter(Q(title__icontains=q) | Q(name__icontains=q))
  for event in event_search:
        event.month = datetime.date(event.date.year, event.date.month, event.date.day).strftime("%b")
  count = len(event_search)
  return render(request, template, {'event_search':event_search,'count':count, 'cart': cart})


def get_cities(request, template="evento_detail.html"):
    sigla = request.GET.get('sigla')
    list_city = Cidade.objects.filter(sigla__exact=sigla).order_by('name')
    cities = [x.name for x in list_city]
    cart_event_form = CartAddOrderItemForm()
    
    the_data = json.dumps({
        'results': cities,
        'cart_event_form': cart_event_form
    })
    return HttpResponse(the_data, content_type='application/json')
  

evento/templates/evento.html
{% extends "base.html" %}
{% load staticfiles %}

{% block middle %}
<section style="margin-top:120px">
    <div class="container">
        <form>
            <div class="form-group">
                <label for="exampleFormControlInput1">Email address</label>
                <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Example select</label>
                <select class="form-control" id="exampleFormControlSelect1">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect2">Example multiple select</label>
                <select multiple class="form-control" id="exampleFormControlSelect2">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Example textarea</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
        </form>
        <button class="btn btn-primary" type="button">
            Messages <span class="badge">4</span>
        </button>
    </div>
</section>
{% endblock middle %}

evento/templates/evento_add.html
{% extends 'base.html' %}
{% load i18n avatar_tags %}
{% load staticfiles %}

{% block title %}Evento | Adicionar{% endblock %}
{% block middle %}
<section class="container">
  <div class="row col-md-12 " style="margin-top:60px" ng-controller="myCtrl as vm">
      <div class="col-md-12"> 
        <!-- design process steps--> 
        <!-- Nav tabs -->
        <ul class="nav nav-tabs process-model more-icon-preocess" role="tablist">
          <li role="presentation" class="active"><a href="#discover" aria-controls="discover" role="tab" data-toggle="tab"><i class="fa fa-question" aria-hidden="true"></i>
            <p>O que?</p>
            </a></li>
          <li role="presentation"><a href="#strategy" aria-controls="strategy" role="tab" data-toggle="tab"><i class="fa fa-map-marker" aria-hidden="true"></i>
            <p>Onde?</p>
            </a></li>
        </ul>
        <!-- end design process steps--> 
      </div>
        <!-- Tab panes -->
        <div class="tab-content">

          <div role="tabpanel" class="tab-pane col-md-12 active" id="discover">
            <div class="row">
              <div class="card" style="width:700px" >
                <div class="mdl-card__title" style="background-color:rgb(63,81,181)">
                  <h2 class="mdl-card__title-text" style="color:white">Informações</h2>
                </div>
                <div class="card-body">

                  <form method="post" id="save_event" action="{% url 'event_browse' %}" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="mdl-textfield mdl-js-textfield mdc-text-field--outlined mdl-textfield--floating-label">
                      <input class="mdl-textfield__input" type="text" required id="id_name" name="name">
                      <label class="mdl-textfield__label" for="id_name">Nome</label>
                    </div>
                    
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <input type="text" name="title" required id="id_title" aria-label="Título" class="mdl-textfield__input"></input>
                      <label class="mdl-textfield__label" for="id_title">Título</label>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select">
                        <input type="text" value="" class="mdl-textfield__input" id="category" readonly>
                        <input type="hidden" required value="" name="category">
                        <label for="category" class="mdl-textfield__label">Categoria</label>
                        <ul for="category" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                        {% for category in categories %}
                            <li class="mdl-menu__item" data-val="{{ category.id }}">{{ category.identifier }}</li>
                        {% endfor %}
                        </ul>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield getmdl-select">
                        <input type="text" value="" class="mdl-textfield__input" id="type_event" readonly>
                        <input type="hidden" required value="" name="type_event">
                        <label for="type_event" class="mdl-textfield__label">Tipo</label>
                        <ul for="type_event" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                        {% for type_event in types %}
                            <li class="mdl-menu__item" data-val="{{ type_event.id }}">{{ type_event.identifier }}</li>
                        {% endfor %}
                        </ul>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height">
                        <input type="text" value="" class="mdl-textfield__input" onchange="getCity(this)" id="state" readonly>
                        <input type="hidden" required value="" name="state">
                        <label for="state" class="mdl-textfield__label">Estado</label>
                        <ul for="state" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                        {% for state in list_state %}
                            <li class="mdl-menu__item" data-val="{{ state.sigla }}">{{ state.sigla }}</li>
                        {% endfor %}
                        </ul>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <input type="text" value="" name="city" class="mdl-textfield__input" id="city" onkeyup="autosearch(this)" url="autocomplete_city">
                        <label for="city" class="mdl-textfield__label">Cidade</label>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <input type="text" name="short_description" required id="id_short_description" aria-label="Pequena descrição" onkeyup="autosearch(this)" url="autocomplete_city" class="mdl-textfield__input"></input>
                      <label class="mdl-textfield__label" for="id_short_description">Resumo Evento</label>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" style="display:none">
                      <input type="text" name="description" id="id_description" aria-label="Pequena descrição" onkeyup="autosearch(this)" url="autocomplete_city" class="mdl-textfield__input"></input>
                      <label class="mdl-textfield__label" for="id_description">Resumo Evento</label>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <input type="date" name="start_date" required id="id_start_date" aria-label="Descrição" class="mdl-textfield__input"></input>
                      <label class="mdl-textfield__label" for="id_start_date">Data de inicio</label>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <input type="date" name="end_date" required id="id_end_date" aria-label="Descrição" class="mdl-textfield__input"></input>
                      <label class="mdl-textfield__label" for="id_end_date">Data do termino</label>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <input type="text" name="street_name" required id="id_street_name" aria-label="Endereco" class="mdl-textfield__input"></input>
                      <label class="mdl-textfield__label" for="id_street_name">Endereco</label>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <input type="text" name="cep" pattern="-?[0-9]*(\.[0-9]+)?" data-mask="999.999.999-99" id="id_cep" aria-label="CEP" class="mdl-textfield__input"></input>
                      <label class="mdl-textfield__label" for="id_cep">CEP</label>
                      <span class="mdl-textfield__error">Atenção utilize apenas numeros!</span>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <input type="number" name="number" required id="id_number" aria-label="Numero" class="mdl-textfield__input"></input>
                      <label class="mdl-textfield__label" for="id_number">Número</label>
                    </div>


                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <input type="date" name="date" required id="id_date" aria-label="Data" class="mdl-textfield__input"></input>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <input type="number" name="price" required id="id_price" aria-label="Numero" class="mdl-textfield__input"></input>
                      <label class="mdl-textfield__label" for="id_price">Preço Cupom</label>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <input type="file" name="image_file" required id="id_image_file" aria-label="Imagem" class="mdl-textfield__input" accept="image/jpeg, image/png, image/jpg"></input>
                    </div>

                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" type="submit">Salvar</button>
                  </form>
                </div>
              </div>

              <div class="card" style="350px">
                <div class="mdl-card__title" style="background-color:rgb(255,64,129)">
                  <h2 class="mdl-card__title-text" style="color:white">Preview</h2>
                </div>
                <div class="card-body">
                  <div class="swiper-slide featured-event-box">
                      <a href="https://www.sympla.com.br/farmer-friends-tour---4-edicao__310823">
                          <div class="event-image-box" id="image_preview" style="background-image: url({% static 'projeto_tg/images/p7.jpg' %});"></div>
                          <div class="event-name" id="model-event-name">
                              <p>Farmer Friends Tour - 4ª Edição</p>
                          </div>
                          <div class="calendar-box">
                              <div class="calendar-month">Jun </div>
                              <div class="calendar-day">28 </div>
                          </div>
                          <div class="event-local-box">
                              <div class="uppercase line">
                                  <p>Urban Farmcy</p>
                              </div>
                              <div class="line"><i class="fa fa-clock-o color-grey" style="padding-right: 2px;"></i>13h <i class="fa fa-map-marker color-grey" style="padding: 40px;"></i>Porto Alegre, RS </div>
                          </div>
                      </a>
                  </div>
                </div>
                
              </div>
            </div>
          </div>

          <div role="tabpanel" class="tab-pane col-md-12" id="strategy">
            <div class="row">
              <div class="card" style="width:1050px">
                <div class="mdl-card__title" style="background-color:rgb(63,81,181)">
                  <h2 class="mdl-card__title-text" style="color:white">Corpo descritivo</h2>
                </div>
                <div class="card-body">
                  <textarea name="editor_1"></textarea>
                </div>
              </div>
            </div>
          </div>

          <div role="tabpanel" class="tab-pane" id="optimization">
            <div class="design-process-content">
              <form>

                <div class="input-group mb-3 ">
                  <div class="input-group-prepend">
                    <span class="input-group-text">Endereco</span>
                  </div>
                  <input type="text" name="street_name" required id="id_street_name" aria-label="Endereco" class="form-control"></input>
                </div>

                <div class="input-group mb-3 ">
                  <div class="input-group-prepend">
                    <span class="input-group-text">CEP</span>
                  </div>
                  <input type="number" name="cep" data-mask="99999-999" required id="id_cep" aria-label="CEP" class="form-control"></input>
                </div>
                
                <div class="input-group mb-3 ">
                  <div class="input-group-prepend">
                    <span class="input-group-text">Número</span>
                  </div>
                  <input type="number" name="number" required id="id_number" aria-label="Numero" class="form-control"></input>
                </div>

              </form>
            </div>
          </div>

          <div role="tabpanel" class="tab-pane" id="content">
            <div class="design-process-content">
              <h3 class="semi-bold">Content</h3>
              <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincid unt ut laoreet dolore magna aliquam erat volutpat</p>              
              </div>
          </div>

          <div role="tabpanel" class="tab-pane" id="reporting">
            <div class="design-process-content">
              <h3>Reporting</h3>
              <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincid unt ut laoreet dolore magna aliquam erat volutpat. </p>
          </div>
          
        </div>
      </div>

      {% block extra_script %}
      <script>
          $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {

              var href = $(e.target).attr('href');
              var $curr = $(".process-model  a[href='" + href + "']").parent();

              $('.process-model li').removeClass();

              $curr.addClass("active");
              $curr.prevAll().addClass("visited");
          });

          $('.mdc-text-field').on('click',(e) => {
            mdc.textField.MDCTextField.attachTo(e.currentTarget)
          })
          {% include 'autocomplete.js' %}
      </script>
      {% endblock extra_script %}
  </div>
</section>

{% endblock middle %}

evento/templates/evento_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block css %}
  <link href="{% static 'projeto_tg/css/event_detail.css' %}" rel="stylesheet" />
{% endblock %}
{% block title %}Evento | Detalhes{% endblock %}
{% block middle %}
<div>
  <style>
  /*Seção detalhes do evento*/
  .header-banner {
      background-color: #333;
      background-image: url('/uploaded/{{ event.image_file }}');
      background-position: center;
      background-repeat: no-repeat;
      width: 100%;
      height: 300px;
    }
    .header-banner h1 {
      background-color: rgb(63,81,181);
      color: #fff;
      padding: 0 1rem;
      position: absolute;
      top: 22rem; 
      left: 2rem;
    }
    .header-banner .mdc-card {
      padding: 0 1rem;
      position: absolute;
      top: 22rem; 
      right: 2rem;
    }
    
    
    .fixed-card {
      position: fixed;
      top: 0;
      right: 2rem;
    }
    
    
    span {cursor:pointer; }
    .number{
      margin:10px;
    }
    .minus{
      width:30px;
      height:30px;
      background:rgb(255,64,129);
      color:white;
      border-radius:4px;
      border:1px solid #ddd;
      display: inline-block;
      vertical-align: middle;
      text-align: center;
    }
    .plus{
      width:30px;
      height:30px;
      background:rgb(63,81,181);
      color:white;
      border-radius:4px;
      border:1px solid #ddd;
      display: inline-block;
      vertical-align: middle;
      text-align: center;
    }
    div > input{
      height:34px;
      width: 100px;
      text-align: center;
      font-size: 26px;
      border:1px solid #ddd;
      border-radius:4px;
      display: inline-block;
      vertical-align: middle;
    }
    /*Fim seção datelhes do evento*/
  </style>
  <div class="header-banner" style="margin-top:50px">
      <h1>{{ event.title }}</h1>

      <div class="mdc-card mdc-card--outlined" id="card_event" style="width: 18rem;">
        <img src="/uploaded/{{ event.image_file }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ event.name }}</h5>
          <p class="card-text" style="font-size:14px;color:black"><strong>Preço:</strong> R$ {{ event.price }}</p>
          
          <form action="{% url "cart:cart_add" event.id_hash %}" method="post">
              {% csrf_token %}
              <div class="number">
                <span class="minus"><i class="fa fa-minus fa-1x" style="margin-top:8px"></i></span>
                <input type="number" name="quantity" value="1"/>
                <span class="plus"><i class="fa fa-plus fa-1x" style="margin-top:8px"></i></span>
              </div>
              {% buttons %}
                  <button type="submit" class="btn btn-success btn-product">
                      <span class="fa fa-shopping-cart fa-1x"></span> Adicionar ao carrinho
                  </button>
              {% endbuttons %}
          </form>
        </div>
          
      </div>

  </div>
</div>
<section class="container" style="margin-top:40px;width:60%">
  {% autoescape off %}
    {{ event.description }}
  {% endautoescape %}
</section>
<script>
  $(window).scroll(function(){
      if ($(window).scrollTop() >= 10) {
          $('#card_event').addClass('fixed-card')
      }
      else {
          $('nav').removeClass('fixed-header');
      }
  });
  $(document).ready(function() {
    $('.minus').click(function () {
      var $input = $(this).parent().find('input');
      var count = parseInt($input.val()) - 1;
      count = count < 1 ? 1 : count;
      $input.val(count);
      $input.change();
      return false;
    });
    $('.plus').click(function () {
      var $input = $(this).parent().find('input');
      $input.val(parseInt($input.val()) + 1);
      $input.change();
      return false;
    });
  });
</script>
{% endblock middle %}

evento/templates/evento_list.html
{% extends 'base.html' %}
{% load i18n avatar_tags %}
{% load staticfiles %}

{% block title %}Evento | Resultados{% endblock %}
{% block middle %}
<div style="margin-top:150px" class="container">
    <h3>{{ count }} Resultado{{ count|pluralize:"s" }}</h3>
    <div class="row col-md-12">
    {% for evt in event_search %}
        <div class="swiper-slide featured-event-box col-md-4">
                <a href="{% url 'event_detail' event=evt.id_hash %}" >
                        <div class="event-image-box" style="background-image: url('/uploaded/{{ evt.image_file }}');"></div>
                        <div class="event-name">
                        <p>{{ evt.title }}</p>
                        </div>
                        <div class="calendar-box">
                        <div class="calendar-month">{{ evt.month }}</div>
                        <div class="calendar-day">{{ evt.date.day }}</div>
                        </div>
                        <div class="event-local-box">
                        <div class="uppercase line">
                                <p>{{ evt.address.city.name }} - {{ evt.address.city.sigla }}</p>
                        </div>
                        <div class="line"><i class="fa fa-clock-o color-grey" style="padding-right: 2px;"></i>13h <i class="fa fa-map-marker color-grey" style="padding: 10px;"></i>{{ evt.address.city.name }} , {{ evt.address.city.sigla }}</div>
                        </div>
                </a>
        </div>
    {% empty %}
            <p>Nenhum resultado encontrado!</p>
    {% endfor %}
    </div>
</div>
{% endblock middle %}

evento/templates/evento_upload.html
{% load staticfiles %}

<section id="drop-zone">
  <h3><i class="fa fa-cloud-upload"></i><br />{% trans "Cole os arquivos aqui" %}</h3>
</section>